// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Endy Apinageri",
            "email": "apinaendy@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Accept JSON data of User Login objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Handle unique Unique User Login",
                "parameters": [
                    {
                        "description": "The Tutor Login Data",
                        "name": "StudentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.LoginData"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/resetpassword": {
            "post": {
                "description": "Accept JSON data of User Reset password objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Handle resetting a user password",
                "parameters": [
                    {
                        "description": "The User Data",
                        "name": "StudentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.ResetPassword"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Accept JSON data of Student User objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Handle unique User Registration",
                "parameters": [
                    {
                        "description": "The Student Registration Data",
                        "name": "StudentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegistrationData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.UserRegistrationData"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/tutor/signup": {
            "post": {
                "description": "Accept JSON data of Tutor Unique objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Handle unique Tutor Registration",
                "parameters": [
                    {
                        "description": "The Tutor Registration Data",
                        "name": "TutorRegistration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TutorRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.TutorRegistration"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/verifyotp": {
            "post": {
                "description": "Accept JSON data of User Reset password objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Handle verifying user otp",
                "parameters": [
                    {
                        "description": "The User Verification Data",
                        "name": "StudentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerifyUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.VerifyUser"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/student/curriculum/": {
            "get": {
                "description": "Gets the list of all curricul courses  being taken by the student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Handles getting student curriculum",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.StudentCurriculum"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/student/examination/": {
            "post": {
                "description": "Accept JSON data for examination objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Handle apply for student examination",
                "parameters": [
                    {
                        "description": "The Student Examination Data",
                        "name": "ExaminationPreparationData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExamPreparation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.ExamPreparation"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/student/tutor/request": {
            "post": {
                "description": "Accept JSON data for new tutor request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Handle student request for new tutor",
                "parameters": [
                    {
                        "description": "The Student Examination Data",
                        "name": "RequestData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestTutor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.RequestTutor"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/tutor/dashboard/": {
            "get": {
                "description": "Accept JSON data for examination objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tutor"
                ],
                "summary": "Handle apply for student examination",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.TutorDashboard"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/user/contactus/": {
            "post": {
                "description": "Accept JSON data for contact details and message objects then returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hybrid APIs"
                ],
                "summary": "Handle contact us request",
                "parameters": [
                    {
                        "description": "The Task Data",
                        "name": "ContactUs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContactUs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.ContactUs"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/user/studyabroad/": {
            "post": {
                "description": "Accept JSON data for study details objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hybrid APIs"
                ],
                "summary": "Handle data to process abroad study",
                "parameters": [
                    {
                        "description": "The Task Data",
                        "name": "StudyAbroadData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StudyAbroad"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.StudyAbroad"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/user/task/": {
            "post": {
                "description": "Accept JSON data for examination objects and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hybrid APIs"
                ],
                "summary": "Handle adding task for users",
                "parameters": [
                    {
                        "description": "The Task Data",
                        "name": "TaskData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Check Response Message",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ContactUs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "models.ExamPreparation": {
            "type": "object",
            "properties": {
                "class_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "exam_cost": {
                    "type": "string"
                },
                "exam_id": {
                    "type": "string"
                },
                "exam_profile": {
                    "type": "string"
                },
                "ezam_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_tutor": {
                    "type": "boolean"
                },
                "student_id": {
                    "description": "logged in user unique id",
                    "type": "string"
                },
                "study_pack": {
                    "type": "boolean"
                },
                "training_duration": {
                    "type": "string"
                },
                "training_type": {
                    "type": "string"
                },
                "tutor_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.LoginData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.RequestTutor": {
            "type": "object",
            "properties": {
                "exam_id": {
                    "type": "string"
                },
                "exam_type": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "models.ResetPassword": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "reset_password_link": {
                    "type": "string"
                }
            }
        },
        "models.ResponseBody": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "object"
                },
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.StudentCurriculum": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "class_type": {
                    "type": "string"
                },
                "subjject": {
                    "type": "string"
                }
            }
        },
        "models.StudyAbroad": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "country_of_study": {
                    "type": "string"
                },
                "course": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "degree_level": {
                    "type": "string"
                },
                "degree_prgramme": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "educational_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "enrollement_year": {
                    "type": "string"
                },
                "enrollment_term": {
                    "type": "string"
                },
                "financial_status": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "graduation_year": {
                    "type": "string"
                },
                "high_school": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "marital_status": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "study_model": {
                    "type": "string"
                },
                "university_name": {
                    "type": "string"
                },
                "year_of_admission": {
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "task": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.TutorDashboard": {
            "type": "object",
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserData"
                    }
                },
                "task": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Task"
                    }
                }
            }
        },
        "models.TutorRegistration": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "nigerian_resident": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "residence": {
                    "type": "string"
                },
                "state_of_residence": {
                    "type": "string"
                },
                "tutor_id": {
                    "type": "string"
                },
                "tutor_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.UserData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                }
            }
        },
        "models.UserRegistrationData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                }
            }
        },
        "models.VerifyUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "verification_otp": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "petstore.swagger.io",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "FNGC Backend Service",
	Description: "This is official backend documentation for the fngc software",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
