basePath: /v1
definitions:
  models.LoginData:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.ResetPassword:
    properties:
      new_password:
        type: string
      old_password:
        type: string
      reset_password_link:
        type: string
    type: object
  models.ResponseBody:
    properties:
      body:
        type: object
      code:
        type: integer
      message:
        type: string
    type: object
  models.UserRegistrationData:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      user_type:
        type: string
    type: object
  models.VerifyUser:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      verification_otp:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: apinaendy@gmail.com
    name: Endy Apinageri
  description: This is official backend documentation for the swift medics backend
    system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swift medics Backend API Service
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Accept JSON data of User Login objects and returns valid response
      parameters:
      - description: The Tutor Login Data
        in: body
        name: StudentData
        required: true
        schema:
          $ref: '#/definitions/models.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.LoginData'
        "400":
          description: Check Response Message
          schema:
            $ref: '#/definitions/models.ResponseBody'
      summary: Handle unique Unique User Login
      tags:
      - Authorization
  /auth/resetpassword:
    post:
      consumes:
      - application/json
      description: Accept JSON data of User Reset password objects and returns valid
        response
      parameters:
      - description: The User Data
        in: body
        name: StudentData
        required: true
        schema:
          $ref: '#/definitions/models.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.ResetPassword'
        "400":
          description: Check Response Message
          schema:
            $ref: '#/definitions/models.ResponseBody'
      summary: Handle resetting a user password
      tags:
      - Authorization
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Accept JSON data of User objects and returns valid response
      parameters:
      - description: The User Registration Data
        in: body
        name: UserData
        required: true
        schema:
          $ref: '#/definitions/models.UserRegistrationData'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.UserRegistrationData'
        "400":
          description: Check Response Message
          schema:
            $ref: '#/definitions/models.ResponseBody'
      summary: Handle unique User Registration
      tags:
      - Authorization
  /auth/verifyotp:
    post:
      consumes:
      - application/json
      description: Accept JSON data of User Reset password objects and returns valid
        response
      parameters:
      - description: The User Verification Data
        in: body
        name: StudentData
        required: true
        schema:
          $ref: '#/definitions/models.VerifyUser'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.VerifyUser'
        "400":
          description: Check Response Message
          schema:
            $ref: '#/definitions/models.ResponseBody'
      summary: Handle verifying user otp
      tags:
      - Authorization
swagger: "2.0"
